const wordList = [
  "dream theater",
  "iron maiden",
  "metallica",
  "death angel",
  "morbid angel",
  "death",
  "slayer",
  "testament",
  "entombed",
  "cynic",
  "obituary",
  "sadus",
  "atheist",
  "sepultura",
  "pantera",
  "steve vai",
  "soundgarden",
  "metal church",
  "toxik",
  "cacophony",
  "racer-x",
  "forbidden",
  "judas priest",
  "motorhead",
  "black sabbath",
  "anthrax",
  "venom",
  "Queensryche",
  "celtic frost",
  "diamond head",
  "exodus",
  "kreator",
  "coroner",
  "death angel",
  "dark angel",
  "fates warning",
  "carcass",
  "arch enemy",
  "nuclear assault",
  "napalm death",
  "possessed",
  "helstar",
  "machine head",
];
